[package]
name = "insanity"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = "3.0.0-beta.2"
cpal = "0.13.4"
rand = "0.8.4"
serde = { version = "1.0.127", features = ["derive"] }
snap = "1"
wav = "1.0.0"