[package]
name = "insanity"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
clap = "3.0.14"
cpal = "0.13.4"
crossbeam = "0.8"
flate2 = "1.0"
nnnoiseless = "0.3.2"
rand = "0.8.4"
serde = { version = "1.0.127", features = ["derive"] }
wav = "1.0.0"
itertools = "0.10.1"
zstd = "0.9"
crossterm = "0.21.0"
tokio = { version = "1", features = ["full"] }
tui = { version = "0.16", default-features = false, features = ["crossterm"] }
nanoid = "0.4.0"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
webpki = { version = "0.21", default-features = true }
rcgen = "0.8.13"
futures-util = "0.3.17"
send_safe = { git = "https://github.com/nicolaschan/send_safe.git" }
libtor = { version = "46.6.0+0.4.6.6", features = ["vendored-openssl"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
dirs = "3.0.2"
warp = "0.3.1"
stunclient = "0.3"
reqwest = { version = "0.11", features = ["socks", "json"] }
serde_json = "1.0.67"
openssl = { version = "0.10", features = ["vendored"] }
veq = { git = "https://github.com/nicolaschan/udpp.git" }