[package]
name = "insanity"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = "3.0.0-beta.2"
cpal = "0.13.4"
crossbeam = "0.8"
flate2 = "1.0"
nnnoiseless = "0.3.2"
rand = "0.8.4"
ring = "0.16.20"
serde = { version = "1.0.127", features = ["derive"] }
wav = "1.0.0"
itertools = "0.10.1"
zstd = "0.9"
crossterm = "0.21.0"
tokio = { version = "1", features = ["full"] }
tui = { version = "0.16", default-features = false, features = ["crossterm"] }
nanoid = "0.4.0"
quinn = "0.7.2"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
webpki = { version = "0.21", default-features = true }
rcgen = "0.8.13"
futures-util = "0.3.17"
send_safe = { git = "https://github.com/nicolaschan/send_safe.git" }
libtor = "46.6.0+0.4.6.6"