name: Linux musl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libasound2-dev
    - name: Rustup Toolchain
      run: rustup toolchain install stable-x86_64-unknown-linux-musl
    - name: Rustup Target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --release --verbose --target x86_64-unknown-linux-musl
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: insanity-musl
        path: target/x86_64-unknown-linux-musl/release/insanity
