name: Linux musl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      run: docker build -t insanity-musl -f Dockerfile.alpine .
    - name: Copy artifact
      run: |
        docker create --name temp-container insanity-musl
        docker cp temp-container:/usr/local/cargo/bin/insanity ./insanity
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: insanity-musl
        path: insanity
