name: macOS x86

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest-large

    steps:
    - uses: actions/checkout@v4
    - name: Rustup Toolchain
      run: rustup toolchain install stable-x86_64-apple-darwin
    - name: Rustup Target
      run: rustup target add x86_64-apple-darwin
    - name: Build
      run: cargo +stable-x86_64-apple-darwin build --release --verbose --target x86_64-apple-darwin
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: insanity
        path: target/x86_64-apple-darwin/release/insanity
