name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/checkout@v3
    - name: Rustup Toolchain
      run: rustup default stable-x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --verbose
      
