name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2.2.0
      with:
        version: 12.2.0 
        platform: x64
    - uses: actions/checkout@v3
    - name: Rustup Toolchain
      run: rustup toolchain install nightly-x86_64-pc-windows-gnu
    - name: Rustup Target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo +nightly-x86_64-pc-windows-gnu build --verbose --target x86_64-pc-windows-gnu
      
